// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxwgoyerlskbfztnurjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4d2dveWVybHNrYmZ6dG51cmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzcyODIsImV4cCI6MjA3MDc1MzI4Mn0.WJNDXRuuCv2Mank_kKCssfquC48EDf6DJYjk-NoGuug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});